---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: centos7
    image: docker.io/geerlingguy/docker-centos7-ansible
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos8
    command: /sbin/init
    image: docker.io/geerlingguy/docker-centos8-ansible
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: amazonlinux2
    image: docker.io/geerlingguy/docker-amazonlinux2-ansible
    command: /sbin/init
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
scenario:
  name: default
verifier:
  name: ansible
  directory: ../resources/tests
